### ISSUE TITLE
ArgoCD repository problem

### ISSUE THREAD

**Issue by clickersmudge** [DevOps-Nirvana/Kubernetes-Volume-Autoscaler#23]
**Describe the bug**
Problem with the repository when installing with ArgoCD

```
Unable to create application: application spec for volume-autoscaler is invalid: InvalidSpecError: Unable to generate manifests in volume-autoscaler: rpc error: code = PermissionDenied desc = helm repos https://devops-nirvana.s3.amazonaws.com/helm-charts/ are not permitted in project 'prod'
```

```
Unable to create application: application spec for volume-autoscaler is invalid: InvalidSpecError: Unable to generate manifests in volume-autoscaler: rpc error: code = PermissionDenied desc = helm repos https://devops-nirvana.s3.amazonaws.com/helm-charts/index.yaml are not permitted in project 'prod'
```

**To Reproduce**
I set up the whole deployment in Argo CD as helm-dependency in accordance with the example (https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency).

Create Chart.yaml
```
apiVersion: v2
name: volume-autoscaler
description: Volume Autoscaler scales Kubernetes volumes up automatically based on metrics from Prometheus, helm chart based on Universal Helm Charts from DevOps Nirvana

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0.8"

dependencies:
- name: volume-autoscaler
  version: 1.0.8
  repository: https://devops-nirvana.s3.amazonaws.com/helm-charts/
```

**Expected behavior**
A working installation using ArgoCD

**Screenshots**
![obraz](https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/assets/113194014/1e7d508d-a4a2-4101-996e-9defe843443f)

**Comment by clickersmudge** [comment]
I made a mistake. It works

Valid Chart.yaml
```
apiVersion: v2
name: volume-autoscaler
description: Volume Autoscaler scales Kubernetes volumes up automatically based on metrics from Prometheus, helm chart based on Universal Helm Charts from DevOps Nirvana

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0.8"

dependencies:
- name: volume-autoscaler
  version: 1.0.8
  repository: https://devops-nirvana.s3.amazonaws.com/helm-charts/
```

Version `1.0.8` from https://devops-nirvana.s3.amazonaws.com/helm-charts/index.yaml
